### ISSUE TITLE
Add requirements.txt and small fixes

### ISSUE THREAD

**Issue by tdsone** [fteufel/SecretoGen#1]
Hey Felix, 

I set up your repo for our lab and note down a few things others might find helpful as well.

## Add a requirements.txt

I thought it would be a cool idea to have a requirements.txt to make intalling requirements for your project less frustrating. Here's what I needed to run compute_perplexity.py:

```
torch
pandas
tqdm
```

## Fix `compute_perplexity.py`

```
from src.models.seq2seq_default import Seq2SeqTransformer
```

should be

```
from src.models.seq2seq import Seq2SeqTransformer
```

Cheers
Timon

**Comment by fteufel** [comment]
Made some changes to the script and updated the readme - stuff should be more ready to use now.

**Comment by tdsone** [comment]
Thanks! I managed to run your example. We're currently setting up a small interface for our biologists to use it. I'm planning to build a small streamlit interface for it. Do you want do keep this repo "UI-free"? Else I would make a PR in the coming days to contribute the interface.

**Comment by tdsone** [comment]
Closing the issue bc completed - thanks again!

**Comment by fteufel** [comment]
Sounds like a great idea! Totally open to have it in this repo. I guess it would make sense to add another requirements.txt so that the repo can be used the way it is now, but else I wouldn't see a problem with having UI code in here too.

Let me know if I should clean up/ better document anything to make it easier!
